name: flu2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.20.2
  flutter_speed_dial: ^7.0.0
  mobile_scanner: ^7.1.2
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  lottie: ^3.3.2
  flutter_image: 4.1.13
  google_mlkit_text_recognition: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
